name: Semgrep
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["main", "dev"]
  schedule:
    - cron: '20 17 * * *'  # Run daily

permissions:
  security-events: write  # Required for SARIF upload
  contents: read
  actions: read

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:1.162.0@sha256:9349edbadf90c3f3c0c3f55867625354e89680e6fa10d9034042af52fdb0e0d0
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - run: semgrep ci --config=auto --sarif > semgrep.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@e60ea984bd3baa95954f2856bcf24f9eaba46637 # v3
        with:
          sarif_file: semgrep.sarif
        if: always()